"""Cortex CaaS — Import helpers for resumes, LinkedIn, and GitHub."""

from __future__ import annotations

import csv
import io
import json
import re
import urllib.request
import urllib.error
import zipfile
from typing import Any


# ── PDF text extraction ──────────────────────────────────────────────

def extract_text_from_pdf(data: bytes) -> str:
    """Extract text from a PDF file.

    Tries optional ``pypdf`` first, falls back to a simple stdlib-only
    parser that scans for BT/ET text blocks.
    """
    # Try pypdf / PyPDF2 if installed
    for pkg in ("pypdf", "PyPDF2"):
        try:
            mod = __import__(pkg)
            reader = mod.PdfReader(io.BytesIO(data))
            pages = []
            for page in reader.pages:
                txt = page.extract_text()
                if txt:
                    pages.append(txt)
            if pages:
                return "\n\n".join(pages)
        except Exception:
            pass

    # Stdlib fallback: scan for text operands in BT…ET blocks
    return _pdf_fallback_extract(data)


def _pdf_fallback_extract(data: bytes) -> str:
    """Best-effort PDF text extraction using only stdlib.

    Looks for ``(text) Tj`` and ``[(text)] TJ`` operands inside
    BT … ET blocks.  Works for simple, uncompressed text-based PDFs
    (covers most resumes generated by word processors).
    """
    text = data.decode("latin-1", errors="replace")
    blocks: list[str] = []

    # Find all BT…ET blocks
    for m in re.finditer(r"BT\s(.*?)ET", text, re.DOTALL):
        block = m.group(1)
        # Extract (text)Tj operands
        for tj in re.finditer(r"\(([^)]*)\)\s*Tj", block):
            blocks.append(tj.group(1))
        # Extract [(text)] TJ array operands
        for tj_arr in re.finditer(r"\[([^\]]*)\]\s*TJ", block):
            inner = tj_arr.group(1)
            for part in re.finditer(r"\(([^)]*)\)", inner):
                blocks.append(part.group(1))

    return "\n".join(blocks)


# ── DOCX text extraction ────────────────────────────────────────────

def extract_text_from_docx(data: bytes) -> str:
    """Extract text from a DOCX file using only stdlib (zipfile + xml)."""
    import xml.etree.ElementTree as ET

    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            if "word/document.xml" not in zf.namelist():
                return ""
            xml_data = zf.read("word/document.xml")
    except (zipfile.BadZipFile, KeyError):
        return ""

    root = ET.fromstring(xml_data)
    paragraphs: list[str] = []
    for para in root.iter(f"{{{ns['w']}}}p"):
        texts = []
        for t_el in para.iter(f"{{{ns['w']}}}t"):
            if t_el.text:
                texts.append(t_el.text)
        if texts:
            paragraphs.append("".join(texts))

    return "\n\n".join(paragraphs)


# ── Resume text → nodes/edges ───────────────────────────────────────

def parse_resume_text(text: str) -> dict:
    """Run AggressiveExtractor on resume text and return nodes/edges dicts."""
    if not text.strip():
        return {"nodes": [], "edges": [], "source_type": "resume"}

    from cortex.extract_memory import AggressiveExtractor

    extractor = AggressiveExtractor()
    extractor.process_plain_text(text)
    graph = extractor.context.to_graph()

    nodes = []
    for n in graph.nodes.values():
        nodes.append({
            "id": n.id,
            "label": n.label,
            "tags": n.tags,
            "confidence": n.confidence,
            "brief": n.brief,
        })

    edges = []
    for e in graph.edges.values():
        edges.append({
            "id": e.id,
            "source_id": e.source_id,
            "target_id": e.target_id,
            "relation": e.relation,
            "confidence": e.confidence,
        })

    return {"nodes": nodes, "edges": edges, "source_type": "resume"}


# ── LinkedIn data export (zip with CSVs) ────────────────────────────

_LINKEDIN_CSV_MAP = {
    "Profile.csv": "profile",
    "Positions.csv": "positions",
    "Skills.csv": "skills",
    "Education.csv": "education",
    "Languages.csv": "languages",
    "Certifications.csv": "certifications",
    "Connections.csv": "connections",
}


def parse_linkedin_export(zip_data: bytes) -> dict:
    """Parse a LinkedIn data export zip and return nodes/edges."""
    from cortex.graph import make_edge_id, make_node_id_with_tag

    nodes: list[dict] = []
    edges: list[dict] = []
    seen: set[str] = set()

    csvs: dict[str, list[dict]] = {}
    try:
        with zipfile.ZipFile(io.BytesIO(zip_data)) as zf:
            for name in zf.namelist():
                basename = name.rsplit("/", 1)[-1] if "/" in name else name
                if basename in _LINKEDIN_CSV_MAP:
                    raw = zf.read(name).decode("utf-8", errors="replace")
                    reader = csv.DictReader(io.StringIO(raw))
                    csvs[basename] = list(reader)
    except (zipfile.BadZipFile, KeyError):
        return {"nodes": [], "edges": [], "source_type": "linkedin_export"}

    # Identity from Profile.csv
    for row in csvs.get("Profile.csv", []):
        first = row.get("First Name", "")
        last = row.get("Last Name", "")
        name = f"{first} {last}".strip()
        if name and name not in seen:
            nid = make_node_id_with_tag(name, "identity")
            nodes.append({"id": nid, "label": name, "tags": ["identity"],
                          "confidence": 0.95, "brief": "LinkedIn profile name"})
            seen.add(name)

        headline = row.get("Headline", "")
        if headline and headline not in seen:
            nid = make_node_id_with_tag(headline, "professional_context")
            nodes.append({"id": nid, "label": headline,
                          "tags": ["professional_context"],
                          "confidence": 0.9, "brief": "LinkedIn headline"})
            seen.add(headline)

        summary = row.get("Summary", "")
        if summary and summary not in seen:
            nid = make_node_id_with_tag(summary[:80], "professional_context")
            nodes.append({"id": nid, "label": summary[:100],
                          "tags": ["professional_context"],
                          "confidence": 0.85, "brief": summary[:500]})
            seen.add(summary)

    # Positions → professional_context nodes + worked_at edges
    for row in csvs.get("Positions.csv", []):
        title = row.get("Title", "")
        company = row.get("Company Name", "")
        if title and title not in seen:
            nid = make_node_id_with_tag(title, "professional_context")
            nodes.append({"id": nid, "label": title,
                          "tags": ["professional_context"],
                          "confidence": 0.9, "brief": f"Role at {company}"})
            seen.add(title)
        if company and company not in seen:
            nid = make_node_id_with_tag(company, "professional_context")
            nodes.append({"id": nid, "label": company,
                          "tags": ["professional_context"],
                          "confidence": 0.9, "brief": "Company"})
            seen.add(company)
        if title and company:
            src = make_node_id_with_tag(title, "professional_context")
            tgt = make_node_id_with_tag(company, "professional_context")
            eid = make_edge_id(src, tgt, "worked_at")
            edges.append({"id": eid, "source_id": src, "target_id": tgt,
                          "relation": "worked_at"})

    # Skills → technical_expertise nodes + has_skill edges
    for row in csvs.get("Skills.csv", []):
        skill = row.get("Name", row.get("Skill", ""))
        if skill and skill not in seen:
            nid = make_node_id_with_tag(skill, "technical_expertise")
            nodes.append({"id": nid, "label": skill,
                          "tags": ["technical_expertise"],
                          "confidence": 0.85, "brief": "LinkedIn skill"})
            seen.add(skill)

    # Education → education nodes + studied_at edges
    for row in csvs.get("Education.csv", []):
        school = row.get("School Name", "")
        degree = row.get("Degree Name", "")
        if school and school not in seen:
            nid = make_node_id_with_tag(school, "education")
            nodes.append({"id": nid, "label": school, "tags": ["education"],
                          "confidence": 0.9, "brief": f"Education: {degree}"})
            seen.add(school)
        if degree and degree not in seen:
            nid = make_node_id_with_tag(degree, "education")
            nodes.append({"id": nid, "label": degree, "tags": ["education"],
                          "confidence": 0.85, "brief": f"Degree from {school}"})
            seen.add(degree)
        if school and degree:
            src = make_node_id_with_tag(degree, "education")
            tgt = make_node_id_with_tag(school, "education")
            eid = make_edge_id(src, tgt, "studied_at")
            edges.append({"id": eid, "source_id": src, "target_id": tgt,
                          "relation": "studied_at"})

    # Certifications
    for row in csvs.get("Certifications.csv", []):
        cert_name = row.get("Name", "")
        if cert_name and cert_name not in seen:
            nid = make_node_id_with_tag(cert_name, "professional_context")
            nodes.append({"id": nid, "label": cert_name,
                          "tags": ["professional_context"],
                          "confidence": 0.85, "brief": "Certification"})
            seen.add(cert_name)

    # Languages
    for row in csvs.get("Languages.csv", []):
        lang = row.get("Name", "")
        if lang and lang not in seen:
            nid = make_node_id_with_tag(lang, "communication_preferences")
            nodes.append({"id": nid, "label": lang,
                          "tags": ["communication_preferences"],
                          "confidence": 0.85, "brief": "Spoken language"})
            seen.add(lang)

    return {"nodes": nodes, "edges": edges, "source_type": "linkedin_export"}


# ── LinkedIn URL fetch (limited) ────────────────────────────────────

def fetch_linkedin_profile(url: str) -> dict:
    """Fetch minimal LinkedIn profile data from a public profile URL.

    LinkedIn blocks most scraping, so this returns ``limited: True``
    with whatever OG meta tags are available.
    """
    from cortex.graph import make_node_id_with_tag

    if not re.match(r"https?://(www\.)?linkedin\.com/in/", url):
        return {"nodes": [], "edges": [], "source_type": "linkedin_url",
                "limited": True, "error": "Invalid LinkedIn profile URL"}

    nodes: list[dict] = []
    try:
        req = urllib.request.Request(url, headers={
            "User-Agent": "Mozilla/5.0 (compatible; CortexBot/1.0)",
        })
        with urllib.request.urlopen(req, timeout=10) as resp:
            html = resp.read(200_000).decode("utf-8", errors="replace")
    except (urllib.error.URLError, OSError):
        return {"nodes": [], "edges": [], "source_type": "linkedin_url",
                "limited": True, "error": "Could not fetch LinkedIn profile"}

    # Extract OG meta tags
    og: dict[str, str] = {}
    for m in re.finditer(
        r'<meta\s+property="og:(\w+)"\s+content="([^"]*)"', html
    ):
        og[m.group(1)] = m.group(2)

    title = og.get("title", "")
    desc = og.get("description", "")

    if title:
        nid = make_node_id_with_tag(title, "identity")
        nodes.append({"id": nid, "label": title, "tags": ["identity"],
                      "confidence": 0.7, "brief": "LinkedIn profile (limited)"})
    if desc:
        nid = make_node_id_with_tag(desc[:80], "professional_context")
        nodes.append({"id": nid, "label": desc[:100],
                      "tags": ["professional_context"],
                      "confidence": 0.6, "brief": desc[:500]})

    return {"nodes": nodes, "edges": [], "source_type": "linkedin_url",
            "limited": True}


# ── GitHub repo fetch ────────────────────────────────────────────────

def fetch_github_repo(url: str, token: str | None = None) -> dict:
    """Fetch GitHub repo metadata via the public API and return nodes/edges."""
    from cortex.graph import make_edge_id, make_node_id_with_tag

    m = re.match(r"https?://github\.com/([^/]+)/([^/\s?#]+)", url)
    if not m:
        return {"nodes": [], "edges": [], "source_type": "github",
                "error": "Invalid GitHub repo URL"}

    owner, repo = m.group(1), m.group(2).rstrip(".git")
    headers: dict[str, str] = {
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "CortexBot/1.0",
    }
    if token:
        headers["Authorization"] = f"token {token}"

    nodes: list[dict] = []
    edges: list[dict] = []

    # Fetch repo metadata
    repo_data: dict[str, Any] = {}
    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{owner}/{repo}", headers=headers)
        with urllib.request.urlopen(req, timeout=10) as resp:
            repo_data = json.loads(resp.read())
    except (urllib.error.URLError, json.JSONDecodeError, OSError) as exc:
        return {"nodes": [], "edges": [], "source_type": "github",
                "error": f"GitHub API error: {exc}"}

    # Create repo node
    desc = repo_data.get("description") or ""
    repo_label = repo_data.get("full_name", f"{owner}/{repo}")
    repo_nid = make_node_id_with_tag(repo_label, "active_priorities")
    stars = repo_data.get("stargazers_count", 0)
    forks = repo_data.get("forks_count", 0)
    brief = f"{desc}  Stars: {stars}, Forks: {forks}".strip()
    nodes.append({
        "id": repo_nid, "label": repo_label,
        "tags": ["active_priorities"],
        "confidence": 0.9, "brief": brief,
    })

    # Fetch languages
    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{owner}/{repo}/languages",
            headers=headers)
        with urllib.request.urlopen(req, timeout=10) as resp:
            langs: dict[str, int] = json.loads(resp.read())
    except (urllib.error.URLError, json.JSONDecodeError, OSError):
        langs = {}

    primary_lang = repo_data.get("language")
    if primary_lang and primary_lang not in langs:
        langs[primary_lang] = 0

    total_bytes = sum(langs.values()) or 1
    for lang, byte_count in langs.items():
        pct = round(byte_count / total_bytes * 100, 1)
        lang_nid = make_node_id_with_tag(lang, "technical_expertise")
        nodes.append({
            "id": lang_nid, "label": lang,
            "tags": ["technical_expertise"],
            "confidence": 0.85, "brief": f"{pct}% of {repo_label}",
        })
        eid = make_edge_id(repo_nid, lang_nid, "uses_language")
        edges.append({"id": eid, "source_id": repo_nid,
                      "target_id": lang_nid, "relation": "uses_language"})

    # Topics
    for topic in repo_data.get("topics", []):
        topic_nid = make_node_id_with_tag(topic, "domain_knowledge")
        nodes.append({
            "id": topic_nid, "label": topic,
            "tags": ["domain_knowledge"],
            "confidence": 0.8, "brief": f"Topic on {repo_label}",
        })
        eid = make_edge_id(repo_nid, topic_nid, "tagged_with")
        edges.append({"id": eid, "source_id": repo_nid,
                      "target_id": topic_nid, "relation": "tagged_with"})

    # Fetch README (best effort)
    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{owner}/{repo}/readme",
            headers=headers)
        with urllib.request.urlopen(req, timeout=10) as resp:
            readme_data = json.loads(resp.read())
            import base64
            readme_text = base64.b64decode(
                readme_data.get("content", "")).decode("utf-8", errors="replace")
            if readme_text.strip():
                readme_nid = make_node_id_with_tag(
                    f"{repo_label}/README", "domain_knowledge")
                nodes.append({
                    "id": readme_nid,
                    "label": f"{repo_label} README",
                    "tags": ["domain_knowledge"],
                    "confidence": 0.75,
                    "brief": readme_text[:500],
                })
    except (urllib.error.URLError, json.JSONDecodeError, OSError, Exception):
        pass

    return {"nodes": nodes, "edges": edges, "source_type": "github"}


# ── File type detection ──────────────────────────────────────────────

def detect_file_type(filename: str, data: bytes) -> str:
    """Detect the type of an uploaded file.

    Returns one of: ``resume_pdf``, ``resume_docx``, ``linkedin_export``,
    ``chat_export``, ``unknown``.
    """
    # PDF magic bytes
    if data[:5] == b"%PDF-":
        return "resume_pdf"

    # Check if it's a zip
    if not zipfile.is_zipfile(io.BytesIO(data)):
        return "unknown"

    try:
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            names = zf.namelist()
            basenames = {n.rsplit("/", 1)[-1] if "/" in n else n for n in names}

            # DOCX: zip with word/document.xml
            if "word/document.xml" in names:
                return "resume_docx"

            # LinkedIn export: contains Profile.csv or Positions.csv
            if "Profile.csv" in basenames or "Positions.csv" in basenames:
                return "linkedin_export"

            # Chat export: contains conversations.json or any .json file
            for name in names:
                if name.endswith("conversations.json"):
                    return "chat_export"
            for name in names:
                if name.lower().endswith(".json"):
                    return "chat_export"
    except zipfile.BadZipFile:
        return "unknown"

    return "unknown"
